import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const COLORS = {
  primary: [0, 0, 0],
  green: [0, 0, 0],
  red: [0, 0, 0],
  blue: [0, 0, 0],
  orange: [0, 0, 0],
  gray: [80, 80, 80],
  darkText: [0, 0, 0],
  lightBorder: [180, 180, 180],
};

const TABLE_BORDER = [0, 0, 0];
const TABLE_TEXT = [0, 0, 0];

// Map unsupported Unicode currency symbols to ASCII-safe alternatives for jsPDF
const SYMBOL_MAP = { '৳': 'Tk ', '₹': 'Rs ', '¥': 'Y ', '€': 'EUR ', '£': 'GBP ' };

function safeSym(symbol) {
  return SYMBOL_MAP[symbol] || symbol;
}

function fmtCur(amt, symbol = 'Tk ') {
  const num = parseFloat(amt);
  if (isNaN(num)) return `${symbol}0.00`;
  return `${symbol}${num.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function fmtDate(d) {
  if (!d) return '';
  try {
    const dt = new Date(d);
    return dt.toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' })
      + '  ' + dt.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true });
  } catch {
    return String(d);
  }
}

function fmtDateOnly(d) {
  if (!d) return '';
  try {
    const dt = new Date(d);
    if (Number.isNaN(dt.getTime())) return String(d);
    const day = String(dt.getDate()).padStart(2, '0');
    const month = String(dt.getMonth() + 1).padStart(2, '0');
    const year = String(dt.getFullYear());
    return `${day}/${month}/${year}`;
  } catch {
    return String(d);
  }
}

function distributeWidths(totalWidth, weights) {
  const totalWeight = weights.reduce((sum, weight) => sum + weight, 0);
  return weights.map((weight) => Number(((totalWidth * weight) / totalWeight).toFixed(2)));
}

/**
 * Generate a PDF report and open it in a new tab.
 */
export function generateReportPdf({
  reportData,
  bank,
  currencySymbol,
  reportTypeLabel,
  showTransactions,
  showExpenses,
  actualHandCash,
  generatedBy,
}) {
  const sym = safeSym(currencySymbol || '৳');
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const marginInch = 0.5;
  const margin = marginInch * 25.4;
  const tableWidth = pageW - margin * 2;
  let y = margin;

  // ── Header ──
  doc.setFontSize(18);
  doc.setTextColor(...COLORS.darkText);
  doc.setFont('helvetica', 'bold');
  doc.text(bank?.name || 'Bank Report', margin, y);
  y += 7;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.gray);
  doc.text(
    `${reportTypeLabel}  |  ${fmtDate(reportData.dateFrom)} - ${fmtDate(reportData.dateTo)}`,
    margin,
    y
  );
  y += 5;
  doc.text(`Generated by: ${generatedBy || 'Unknown'}  |  ${new Date().toLocaleString('en-US', { month: 'short', day: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit', hour12: true })}`, margin, y);
  y += 3;

  // Divider
  doc.setDrawColor(...COLORS.lightBorder);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageW - margin, y);
  y += 6;

  // ── Summary Cards (table-based to avoid overflow) ──
  const cards = [];

  if (showTransactions) {
    cards.push(
      { label: 'Total Deposits', value: fmtCur(reportData.totalDeposits || 0, sym), sub: `${reportData.depositCount || 0} txns`, color: COLORS.green },
      { label: 'Total Withdrawals', value: fmtCur(reportData.totalWithdrawals || 0, sym), sub: `${reportData.withdrawalCount || 0} txns`, color: COLORS.red },
      { label: 'Total Cash In', value: fmtCur(reportData.totalCashIn || 0, sym), sub: `${reportData.cashInCount || 0} txns`, color: COLORS.blue },
    );
  }
  if (showExpenses) {
    cards.push({ label: 'Total Expenses', value: fmtCur(reportData.totalExpenses || 0, sym), sub: `${reportData.expenseCount || 0} items`, color: COLORS.orange });
  }

  // Add mother account balance cards
  if (reportData.motherAccountBalances && reportData.motherAccountBalances.length > 0) {
    reportData.motherAccountBalances.forEach((ma) => {
      cards.push({ label: ma.name, value: fmtCur(ma.balance, sym), sub: ma.account_number || 'Mother A/C', color: COLORS.darkText });
    });
    cards.push({ label: 'Total Mother Balance', value: fmtCur(reportData.totalMotherBalance || 0, sym), sub: 'All Accounts', color: COLORS.primary });
  }

  // Total Balance = Mother Balance + Hand Cash
  const totalBalance = (reportData.totalMotherBalance || 0) + (reportData.handCashBalance || 0);
  cards.push({ label: 'Total Balance', value: fmtCur(totalBalance, sym), sub: 'Mother + Hand Cash', color: COLORS.primary });

  const summaryRows = [];
  for (let i = 0; i < cards.length; i += 2) {
    const left = cards[i];
    const right = cards[i + 1];
    summaryRows.push([
      left ? `${left.label}\n${left.sub}` : '',
      left?.value || '',
      right ? `${right.label}\n${right.sub}` : '',
      right?.value || '',
    ]);
  }

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [['Metric', 'Amount', 'Metric', 'Amount']],
    body: summaryRows,
    styles: {
      fontSize: 8.2,
      cellPadding: 1.8,
      overflow: 'ellipsize',
      textColor: TABLE_TEXT,
      lineColor: TABLE_BORDER,
      lineWidth: 0.1,
      valign: 'middle',
    },
    headStyles: {
      fillColor: [255, 255, 255],
      textColor: TABLE_TEXT,
      fontStyle: 'bold',
      fontSize: 8,
      lineColor: TABLE_BORDER,
      lineWidth: 0.15,
    },
    columnStyles: {
      0: { cellWidth: 40 },
      1: { halign: 'right', cellWidth: 52, fontStyle: 'bold', fontSize: 7.2 },
      2: { cellWidth: 40 },
      3: { halign: 'right', cellWidth: 52, fontStyle: 'bold', fontSize: 7.2 },
    },
    tableWidth,
    alternateRowStyles: { fillColor: [248, 248, 248] },
    theme: 'grid',
  });
  y = doc.lastAutoTable.finalY + 6;

  // ── Actual Hand Cash Verification ──
  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [['Hand Cash Check', 'Amount']],
    body: [
      ['Actual Hand Cash (Counted)', fmtCur(actualHandCash, sym)],
      ['System Hand Cash', fmtCur(reportData.handCashBalance || 0, sym)],
      ['Verification', 'Matched'],
    ],
    styles: {
      fontSize: 8,
      cellPadding: 1.6,
      overflow: 'ellipsize',
      textColor: TABLE_TEXT,
      lineColor: TABLE_BORDER,
      lineWidth: 0.1,
      valign: 'middle',
    },
    headStyles: {
      fillColor: [255, 255, 255],
      textColor: TABLE_TEXT,
      fontStyle: 'bold',
      fontSize: 7.2,
      lineColor: TABLE_BORDER,
      lineWidth: 0.15,
    },
    columnStyles: {
      0: { cellWidth: 122 },
      1: { halign: 'right', cellWidth: 62, fontStyle: 'bold', fontSize: 7.1 },
    },
    tableWidth,
    theme: 'grid',
  });
  y = doc.lastAutoTable.finalY + 6;

  // ── Net Flow ──
  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    body: [['Net Flow', fmtCur(reportData.netFlow || 0, sym)]],
    styles: {
      fontSize: 9,
      cellPadding: 2,
      overflow: 'ellipsize',
      textColor: TABLE_TEXT,
      lineColor: TABLE_BORDER,
      lineWidth: 0.1,
      valign: 'middle',
    },
    columnStyles: {
      0: { cellWidth: 122, fontStyle: 'bold' },
      1: { halign: 'right', cellWidth: 62, fontStyle: 'bold', fontSize: 8.2 },
    },
    tableWidth,
    theme: 'grid',
  });
  y = doc.lastAutoTable.finalY + 6;

  // ── Transaction Details ──
  if (showTransactions && reportData.transactions?.length > 0) {
    if (y > 240) { doc.addPage(); y = 14; }

    doc.setFontSize(12);
    doc.setTextColor(...COLORS.darkText);
    doc.setFont('helvetica', 'bold');
    doc.text('Transaction Details', margin, y);
    y += 2;

    let totalCredit = 0;
    let totalDebit = 0;
    const txnRows = reportData.transactions.map((txn) => {
      const isCredit = txn.type === 'deposit' || txn.type === 'cash_in';
      const isCashIn = txn.type === 'cash_in';
      const amt = Number(txn.amount || 0);
      if (isCredit) totalCredit += amt; else totalDebit += amt;
      const fundInto = isCashIn
        ? (txn.mother_account_id ? (txn.mother_accounts?.name || 'Mother Account') : txn.profit_account_id ? (txn.profit_accounts?.name || 'Profit Account') : 'Hand Cash')
        : '-';
      return [
        fmtDateOnly(txn.created_at),
        txn.trn_id || '-',
        (txn.type || '').replace('_', ' ').replace(/^\w/, (c) => c.toUpperCase()),
        txn.customer_name || '-',
        txn.customer_account || '-',
        txn.mother_accounts?.name || txn.mother_accounts?.account_number || '-',
        fundInto,
        isCashIn && txn.source ? txn.source : '-',
        isCredit ? fmtCur(txn.amount, sym) : '-',
        !isCredit ? fmtCur(txn.amount, sym) : '-',
      ];
    });

    // Add total row
    txnRows.push([
      { content: 'Total', colSpan: 8, styles: { halign: 'right', fontStyle: 'bold' } },
      { content: fmtCur(totalCredit, sym), styles: { halign: 'right', fontStyle: 'bold' } },
      { content: fmtCur(totalDebit, sym), styles: { halign: 'right', fontStyle: 'bold' } },
    ]);

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [['Date (DD/MM/YYYY)', 'TRN ID', 'Type', 'Customer Name', 'Account No.', 'Mother A/C', 'Fund Into', 'Source', 'Credit', 'Debit']],
      body: txnRows,
      styles: {
        fontSize: 7,
        cellPadding: 1.2,
        overflow: 'linebreak',
        textColor: TABLE_TEXT,
        lineColor: TABLE_BORDER,
        lineWidth: 0.1,
        valign: 'middle',
      },
      headStyles: {
        fillColor: [255, 255, 255],
        textColor: TABLE_TEXT,
        fontStyle: 'bold',
        fontSize: 6.7,
        lineColor: TABLE_BORDER,
        lineWidth: 0.15,
      },
      columnStyles: {
        0: { cellWidth: 16 },
        1: { cellWidth: 14 },
        2: { cellWidth: 15 },
        3: { cellWidth: 28 },
        4: { cellWidth: 20 },
        5: { cellWidth: 19 },
        6: { cellWidth: 19 },
        7: { cellWidth: 12 },
        8: { halign: 'right', cellWidth: 21, fontSize: 6.7, fontStyle: 'bold' },
        9: { halign: 'right', cellWidth: 20, fontSize: 6.7, fontStyle: 'bold' },
      },
      tableWidth,
      theme: 'grid',
    });
    y = doc.lastAutoTable.finalY + 6;
  }

  // ── Expense Details ──
  if (showExpenses && reportData.expenses?.length > 0) {
    if (y > 240) { doc.addPage(); y = 14; }

    doc.setFontSize(12);
    doc.setTextColor(...COLORS.darkText);
    doc.setFont('helvetica', 'bold');
    doc.text('Expense Details', margin, y);
    y += 2;

    const expColumnWidths = distributeWidths(tableWidth, [0.95, 0.85, 1.0, 1.45, 0.95, 0.95, 1.35]);

    const expRows = reportData.expenses.map((exp) => [
      fmtDateOnly(exp.created_at),
      exp.trn_id || '-',
      exp.expense_categories?.name || '-',
      exp.description || '-',
      (exp.deduct_from || '').replace('_', ' ').replace(/^\w/, (c) => c.toUpperCase()),
      exp.mother_accounts?.name || exp.mother_accounts?.account_number || exp.profit_accounts?.name || '-',
      fmtCur(exp.amount, sym),
    ]);

    // Add total expense row
    expRows.push([
      { content: 'Total Expense', colSpan: 6, styles: { halign: 'right', fontStyle: 'bold' } },
      { content: fmtCur(reportData.totalExpenses || 0, sym), styles: { halign: 'right', fontStyle: 'bold' } },
    ]);

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [['Date (DD/MM/YYYY)', 'TRN ID', 'Category', 'Description', 'Deducted From', 'Account', 'Amount']],
      body: expRows,
      styles: {
        fontSize: 7.2,
        cellPadding: 1.6,
        overflow: 'linebreak',
        textColor: TABLE_TEXT,
        lineColor: TABLE_BORDER,
        lineWidth: 0.1,
        valign: 'middle',
      },
      headStyles: {
        fillColor: [255, 255, 255],
        textColor: TABLE_TEXT,
        fontStyle: 'bold',
        fontSize: 6.8,
        lineColor: TABLE_BORDER,
        lineWidth: 0.15,
      },
      tableWidth,
      columnStyles: {
        0: { cellWidth: expColumnWidths[0] },
        1: { cellWidth: expColumnWidths[1] },
        2: { cellWidth: expColumnWidths[2] },
        3: { cellWidth: expColumnWidths[3] },
        4: { cellWidth: expColumnWidths[4] },
        5: { cellWidth: expColumnWidths[5] },
        6: { halign: 'right', cellWidth: expColumnWidths[6], fontSize: 6.7, fontStyle: 'bold' },
      },
      theme: 'grid',
    });
    y = doc.lastAutoTable.finalY + 6;
  }

  // ── Loan Return Details ──
  if (showTransactions && reportData.loanReturns?.length > 0) {
    if (y > 240) { doc.addPage(); y = 14; }

    doc.setFontSize(12);
    doc.setTextColor(...COLORS.darkText);
    doc.setFont('helvetica', 'bold');
    doc.text('Loan Return Details', margin, y);
    y += 2;

    const loanReturnColumnWidths = distributeWidths(tableWidth, [0.9, 0.85, 0.95, 1.4, 1.35, 1.5]);

    const loanReturnRows = reportData.loanReturns.map((ret) => [
      fmtDateOnly(ret.created_at),
      ret.trn_id || '-',
      (ret.returned_by_profile?.full_name || ret.returned_by_profile?.email || ret.returned_by) || '-',
      ret.destination_label || ret.destination_type || '-',
      ret.notes || '-',
      fmtCur(ret.amount, sym),
    ]);

    loanReturnRows.push([
      { content: 'Total Loan Returns', colSpan: 5, styles: { halign: 'right', fontStyle: 'bold' } },
      { content: fmtCur(reportData.totalLoanReturns || 0, sym), styles: { halign: 'right', fontStyle: 'bold' } },
    ]);

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [['Date (DD/MM/YYYY)', 'TRN ID', 'User', 'Destination', 'Notes', 'Amount']],
      body: loanReturnRows,
      styles: {
        fontSize: 7.2,
        cellPadding: 1.6,
        overflow: 'linebreak',
        textColor: TABLE_TEXT,
        lineColor: TABLE_BORDER,
        lineWidth: 0.1,
        valign: 'middle',
      },
      headStyles: {
        fillColor: [255, 255, 255],
        textColor: TABLE_TEXT,
        fontStyle: 'bold',
        fontSize: 6.8,
        lineColor: TABLE_BORDER,
        lineWidth: 0.15,
      },
      tableWidth,
      columnStyles: {
        0: { cellWidth: loanReturnColumnWidths[0] },
        1: { cellWidth: loanReturnColumnWidths[1] },
        2: { cellWidth: loanReturnColumnWidths[2] },
        3: { cellWidth: loanReturnColumnWidths[3] },
        4: { cellWidth: loanReturnColumnWidths[4] },
        5: { halign: 'right', cellWidth: loanReturnColumnWidths[5], fontSize: 6.7, fontStyle: 'bold' },
      },
      theme: 'grid',
    });
    y = doc.lastAutoTable.finalY + 6;
  }

  // ── Signature Section ──
  // ── Signature Section ──
  // Smart rendering: pick the smallest signature block that fits remaining space
  const footerReserve = 12; // reserve space (mm) for footer area
  let remaining = pageH - y - margin - footerReserve;
  const heights = { full: 28, compressed: 16, compact: 8 };
  let sigMode = null;

  if (remaining >= heights.full) {
    sigMode = 'full';
  } else if (remaining >= heights.compressed) {
    sigMode = 'compressed';
  } else if (remaining >= heights.compact) {
    sigMode = 'compact';
  } else {
    // nothing fits: start new page and render full
    doc.addPage();
    y = margin;
    remaining = pageH - y - margin - footerReserve;
    sigMode = 'full';
  }

  if (sigMode === 'compact') {
    y += 6;
    const sigLineW = 40;
    const sigLeftX = margin;
    const sigRightX = pageW - margin - sigLineW;
    doc.setDrawColor(...COLORS.darkText);
    doc.setLineWidth(0.2);
    doc.line(sigLeftX, y, sigLeftX + sigLineW, y);
    doc.line(sigRightX, y, sigRightX + sigLineW, y);
    doc.setFontSize(7);
    doc.setTextColor(...COLORS.darkText);
    doc.text('Agent', sigLeftX, y + 3);
    doc.text('Authorized', sigRightX, y + 3);
  } else if (sigMode === 'compressed') {
    y += 8;
    const sigLineW = 50;
    const sigLeftX = margin;
    const sigRightX = pageW - margin - sigLineW;
    doc.setDrawColor(...COLORS.darkText);
    doc.setLineWidth(0.25);
    // Left
    doc.line(sigLeftX, y, sigLeftX + sigLineW, y);
    doc.setFontSize(7.5);
    doc.setTextColor(...COLORS.darkText);
    doc.text('Signature of Agent / CSO', sigLeftX, y + 3);
    doc.setFontSize(6.5);
    doc.setTextColor(...COLORS.gray);
    doc.text('Name: ____________________', sigLeftX, y + 8);
    // Right
    doc.line(sigRightX, y, sigRightX + sigLineW, y);
    doc.setFontSize(7.5);
    doc.setTextColor(...COLORS.darkText);
    doc.text('Authorized Signature', sigRightX, y + 3);
    doc.setFontSize(6.5);
    doc.setTextColor(...COLORS.gray);
    doc.text('Name: ____________________', sigRightX, y + 8);
  } else {
    // full
    y += 8;
    const sigLineW = 60;
    const sigLeftX = margin;
    const sigRightX = pageW - margin - sigLineW;
    doc.setDrawColor(...COLORS.darkText);
    doc.setLineWidth(0.3);

    // Left: Agent/CSO signature
    doc.line(sigLeftX, y, sigLeftX + sigLineW, y);
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.darkText);
    doc.setFont('helvetica', 'normal');
    doc.text('Signature of Agent / CSO', sigLeftX, y + 4);
    doc.setFontSize(7);
    doc.setTextColor(...COLORS.gray);
    doc.text('Name: ____________________________', sigLeftX, y + 9);
    doc.text('Date: ____________________________', sigLeftX, y + 13);

    // Right: Authorized signature
    doc.line(sigRightX, y, sigRightX + sigLineW, y);
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.darkText);
    doc.setFont('helvetica', 'normal');
    doc.text('Authorized Signature', sigRightX, y + 4);
    doc.setFontSize(7);
    doc.setTextColor(...COLORS.gray);
    doc.text('Name: ____________________________', sigRightX, y + 9);
    doc.text('Date: ____________________________', sigRightX, y + 13);
  }

  // ── Footer on every page ──
  const pageCount = doc.internal.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    const footerY = pageH - margin + 2;
    doc.setFontSize(7);
    doc.setTextColor(...COLORS.gray);
    doc.setFont('helvetica', 'normal');
    doc.text(
      `Generated by ${generatedBy || 'Unknown'}  |  ${bank?.name || 'AgentBank ERP'}  |  Page ${p} of ${pageCount}`,
      pageW / 2,
      footerY,
      { align: 'center' }
    );
    doc.text(
      'Software by: @rhmunna143',
      pageW / 2,
      footerY + 4,
      { align: 'center' }
    );
  }

  // Open in new tab
  const pdfBlob = doc.output('blob');
  const url = URL.createObjectURL(pdfBlob);
  window.open(url, '_blank');
}
